-- MySQL Script generated by MySQL Workbench
-- Seg 03 Out 2016 15:03:22 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema praSempreUFG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema praSempreUFG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `praSempreUFG` DEFAULT CHARACTER SET utf8 ;
USE `praSempreUFG` ;

-- -----------------------------------------------------
-- Table `praSempreUFG`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `praSempreUFG`.`usuario` ;

CREATE TABLE IF NOT EXISTS `praSempreUFG`.`usuario` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `praSempreUFG`.`processo_importacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `praSempreUFG`.`processo_importacao` ;

CREATE TABLE IF NOT EXISTS `praSempreUFG`.`processo_importacao` (
  `id` INT NOT NULL,
  `momento_execucao` DATE NOT NULL,
  `inicio_periodo` DATE NOT NULL,
  `fim_periodo` DATE NOT NULL,
  `quantidade_importados_sucesso` INT NOT NULL,
  `quantidade_importados_dados_incorretos` INT NOT NULL,
  `quantidade_importados_replicados` INT NOT NULL,
  `id_usuario_autorizador` INT NOT NULL,
  PRIMARY KEY (`id`, `momento_execucao`),
  INDEX `fk_processo_importacao_usuario1_idx` (`id_usuario_autorizador` ASC),
  CONSTRAINT `fk_processo_importacao_usuario1`
    FOREIGN KEY (`id_usuario_autorizador`)
    REFERENCES `praSempreUFG`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `praSempreUFG`.`usuario_processo_importacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `praSempreUFG`.`usuario_processo_importacao` ;

CREATE TABLE IF NOT EXISTS `praSempreUFG`.`usuario_processo_importacao` (
  `id_egresso` INT NOT NULL,
  `id_processo_importacao` INT NOT NULL,
  PRIMARY KEY (`id_egresso`, `id_processo_importacao`),
  INDEX `fk_usuario_processo_importacao_processo_importacao1_idx` (`id_processo_importacao` ASC),
  INDEX `fk_usuario_processo_importacao_usuario1_idx` (`id_egresso` ASC),
  CONSTRAINT `fk_usuario_processo_importacao_usuario1`
    FOREIGN KEY (`id_egresso`)
    REFERENCES `praSempreUFG`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_processo_importacao_processo_importacao1`
    FOREIGN KEY (`id_processo_importacao`)
    REFERENCES `praSempreUFG`.`processo_importacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `praSempreUFG`.`instancia_administrativa_ufg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `praSempreUFG`.`instancia_administrativa_ufg` ;

CREATE TABLE IF NOT EXISTS `praSempreUFG`.`instancia_administrativa_ufg` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `praSempreUFG`.`instancia_administrativa_ufg_processo_importacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `praSempreUFG`.`instancia_administrativa_ufg_processo_importacao` ;

CREATE TABLE IF NOT EXISTS `praSempreUFG`.`instancia_administrativa_ufg_processo_importacao` (
  `id_instancia_administrativa_ufg` INT NOT NULL,
  `id_processo_importacao` INT NOT NULL,
  PRIMARY KEY (`id_instancia_administrativa_ufg`, `id_processo_importacao`),
  INDEX `fk_instancia_administrativa_ufg_processo_importacao_pro_idx` (`id_processo_importacao` ASC),
  INDEX `fk_instancia_administrativa_ufg_processo_importacao_ins_idx` (`id_instancia_administrativa_ufg` ASC),
  CONSTRAINT `fk_instancia_administrativa_ufg_processo_importacao_insta1`
    FOREIGN KEY (`id_instancia_administrativa_ufg`)
    REFERENCES `praSempreUFG`.`instancia_administrativa_ufg` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instancia_administrativa_ufg_processo_importacao_proce1`
    FOREIGN KEY (`id_processo_importacao`)
    REFERENCES `praSempreUFG`.`processo_importacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
