CREATE TYPE tipo_evento AS ENUM ('NOTICIA', 'PALESTRA', 'CURSO', 'OPORTUNIDADE DE EMPREGO', 'DIVERSOS');

CREATE TYPE forma_divulgacao AS ENUM ('MENSAGEM', 'NOTICIA', 'AMBOS', 'NENHUMA');

CREATE TYPE escopo_divulgacao AS ENUM ('APENAS EGRESSOS', 'COMUNIDADE', 'FORA DE ESCOPO');

CREATE TYPE tipo_instancia AS ENUM ('REGIONAL', 'UNIDADE', 'CURSO');


CREATE TABLE EVENTO
(
ASSUNTO				            VARCHAR(100)	PRIMARY KEY NOT NULL,
TIPO					            tipo_evento				        NOT NULL,
DESCRICAO				          VARCHAR(500)			        NOT NULL,
DATA_SOLICITA_DIVULGACAO	DATE					            NOT NULL,
SOLICITANTE_DIVULGACAO	  VARCHAR(100)			        NOT NULL,
SOLICITANTE_EMAIL		      VARCHAR(100)			        NOT NULL,
FORMA_DIVULGACAO		      forma_divulgacao			    NOT NULL,
ESCOPO_DIVULGACAO		      escopo_divulgacao			    NOT NULL,
DATA_EXPIRACAO			      DATE
);

CREATE TABLE AREA_DE_CONHECIMENTO
(
NOME 			                VARCHAR(100) 	 	        NOT NULL,
CODIGO 			              INTEGER		PRIMARY KEY 	NOT NULL,
CODIGO_AREA_CONHECIMENTO	INTEGER	REFERENCES AREA_DE_CONHECIMENTO(CODIGO)	
);

CREATE TABLE INSTANCIA_ADMINISTRATIVA_UFG
(
SIGLA_INSTANCIA		  VARCHAR(20)	PRIMARY KEY	NOT NULL,
NOME				        VARCHAR(100)				    NOT NULL,
TIPO				        tipo_instancia					NOT NULL,
DATA_CRIACAO		    DATE						        NOT NULL,
DATA_ENCERRA		    DATE,
EMAIL_INSTITUCIONAL	VARCHAR(100)				    NOT NULL,
URL_INSTITUCIONAL	  VARCHAR(100)				    NOT NULL
);

CREATE TABLE EVENTO_RELACIONADO_A_AREA
(
ASSUNTO 		  VARCHAR(100) REFERENCES EVENTO (ASSUNTO)    NOT NULL,
CODIGO_AREA 	INTEGER	   REFERENCES AREA_DE_CONHECIMENTO  NOT NULL
);

CREATE TABLE EVENTO_INTERESSA_A_INSTANCIA
(
ASSUNTO 		    VARCHAR(100) REFERENCES EVENTO (ASSUNTO)            NOT NULL,
SIGLA_INSTANCIA	VARCHAR(20) REFERENCES INSTANCIA_ADMINISTRATIVA_UFG NOT NULL
);
