CREATE TYPE tipo_evento AS ENUM ('NOTICIA', 'PALESTRA', 'CURSO', 'OPORTUNIDADE DE EMPREGO', 'DIVERSOS');

CREATE TYPE forma_divulgacao AS ENUM ('MENSAGEM', 'NOTICIA', 'AMBOS', 'NENHUMA');

CREATE TYPE escopo_divulgacao AS ENUM ('APENAS EGRESSOS', 'COMUNIDADE', 'FORA DE ESCOPO');

CREATE TYPE tipo_instancia AS ENUM ('REGIONAL', 'UNIDADE', 'CURSO');

CREATE TYPE recebe_divulgacao AS ENUM ('CADA EVENTO', 'DIARIA', 'SEMANAL',
'MENSAL', 'NÃO RECEBE');
 
CREATE TYPE nivel AS ENUM ('BACHARELADO', 'LICENCIATURA', 'APERFEIÇOAMENTO',
'ESPECIALIZAÇÃO', 'MESTRADO', 'DOUTORADO');
 
CREATE TYPE tipo_de_resolucao AS ENUM ('CEPEC', 'CONSUN');
 
CREATE TYPE turno AS ENUM ('MATUTINO', 'VESPERTINO', 'INTEGRAL'); 

CREATE TABLE EVENTO
(
ASSUNTO	VARCHAR(100)	PRIMARY KEY NOT NULL,
TIPO	tipo_evento	NOT NULL,
DESCRICAO	VARCHAR(500)	NOT NULL,
DATA_SOLICITA_DIVULGACAO	TIMESTAMP	NOT NULL,
SOLICITANTE_DIVULGACAO	VARCHAR(100)	NOT NULL,
SOLICITANTE_EMAIL	VARCHAR(30)	NOT NULL,
FORMA_DIVULGACAO	forma_divulgacao	NOT NULL,
ESCOPO_DIVULGACAO	escopo_divulgacao	NOT NULL,
DATA_EXPIRACAO	DATE
);

CREATE TABLE AREA_DE_CONHECIMENTO
(
NOME	VARCHAR(100)	NOT NULL,
CODIGO	INTEGER	PRIMARY KEY NOT NULL,
CODIGO_AREA_CONHECIMENTO	INTEGER	REFERENCES AREA_DE_CONHECIMENTO(CODIGO)	NOT NULL
);

CREATE TABLE INSTANCIA_ADMINISTRATIVA_UFG
(
SIGLA_INSTANCIA	VARCHAR(10)	PRIMARY KEY NOT NULL,
NOME	VARCHAR(100)	NOT NULL,
TIPO	tipo_instancia	NOT NULL,
DATA_CRIACAO	DATE	NOT NULL,
DATA_ENCERRA	DATE,
EMAIL_INSTITUCIONAL	VARCHAR(30)	NOT NULL,
URL_INSTITUCIONAL	VARCHAR(100)	NOT NULL
);

CREATE TABLE EVENTO_RELACIONADO_A_AREA
(
ASSUNTO	VARCHAR(100) REFERENCES EVENTO (ASSUNTO) NOT NULL,
CODIGO_AREA	INTEGER	REFERENCES AREA_DE_CONHECIMENTO(CODIGO) NOT NULL
);

CREATE TABLE EVENTO_INTERESSA_A_INSTANCIA
(
ASSUNTO	VARCHAR(100) REFERENCES EVENTO (ASSUNTO) NOT NULL,
SIGLA_INSTANCIA	VARCHAR(10) REFERENCES INSTANCIA_ADMINISTRATIVA_UFG(SIGLA_INSTANCIA) NOT NULL
);

CREATE TABLE USUARIO
(
EMAIL_PRINCIPAL	VARCHAR(100) NOT NULL,
SENHA	VARCHAR(10)  NOT NULL,
NOME_SOCIAL	VARCHAR(100) NOT NULL,
CPF	INTEGER	PRIMARY KEY NOT NULL,
FOTO_PESSOAL	BYTEA,
RECEBE_DIVULGACAO	recebe_divulgacao NOT NULL,
TIMESTAMP_DE_CADASTRAMENTO	TIMESTAMP NOT NULL,
TIMESTAMP_DE_ULTIMA_ATUALIZACAO	TIMESTAMP NOT NULL,
TIMESTAMP_DE_EXCLUSAO_LOGICA	TIMESTAMP NOT NULL,
SIGLA_INSTANCIA	VARCHAR(10) REFERENCES INSTANCIA_ADMINISTRATIVA_UFG(SIGLA_INSTANCIA) NOT NULL
);
 
CREATE TABLE APROVACAO_DE_DIVULGACAO
(
DIVULGACAO_APROVADA	BOOLEAN NOT NULL,
PARECER_SOBRE_DIVULGACAO	VARCHAR(100) NOT NULL,
DATA_APROVACAO_OU_REJEICAO	DATE NOT NULL,
ASSUNTO_EVENTO	VARCHAR(100) REFERENCES EVENTO (ASSUNTO) NOT NULL,
CPF_USUARIO INTEGER REFERENCES USUARIO (CPF) NOT NULL
);
 
CREATE TABLE CURSO_DA_UFG
(
NIVEL	nivel NOT NULL,
TIPO_DE_RESOLUCAO	tipo_de_resolucao NOT NULL,
NUMERO_DA_RESOLUCAO	INTEGER     	PRIMARY KEY NOT NULL,
PRESENCIAL	BOOLEAN NOT NULL,
TURNO	turno NOT NULL,
CODIGO_AREA	INTEGER	REFERENCES AREA_DE_CONHECIMENTO(CODIGO) NOT NULL
);
