package br.ufg.inf.sempreufg.enums;

public enum ParametrosLogging
{
	LOG_DESTINATION, LOGGING_COLLECTOR, LOG_DIRECTORY, LOG_FILENAME, LOG_ROTATION_AGE, LOG_ROTATION_SIZE, LOG_TRUNCATE_ON_ROTATION, SYSLOG_FACILITY, SYSLOG_IDENT,
		CLIENT_MIN_MESSAGES, LOG_MIN_MESSAGES, LOG_ERROR_VERBOSITY, LOG_MIN_ERROR_STATEMENT, LOG_MIN_DURATION_STATEMENT, SILENT_MODE, DEBUG_PRINT_PARSE, DEBUG_PRINT_REWRITTEN,
		DEBUG_PRETTY_PRINT, LOG_CHECKPOINTS, LOG_CONNECTIONS, LOG_DISCONNECTIONS, LOG_DURATION, LOG_HOSTNAME, LOG_LINE_PREFIX, LOG_LOCK_WAITS, LOG_STATEMENT, LOG_TEMP_FILES,
		LOG_TIMEZONE, APPLICATION_NAME
}
