language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  mariadb: '5.5'
  postgresql: '9.3'
before_script:
  - psql -c 'create database sempreufg;' -U postgres
script:
  - mvn -X -e -B clean package
