language: java
jdk:
       - oraclejdk8
addons:
  mariadb: '5.5'
  postgresql: '9.3'
  sonarqube: true
env:
  global:
    - secure: 9585d2776d0c16c02eefb0456bc46a1e4f0ec12b
before_script:
  - psql --version ;
script:
  - psql -h localhost -U postgres -a -f db/postgres/ddl/create-user-and-db.sql
  - sh db/postgres/postgres.sh
  - mvn -X -e -B clean package sonar:sonar -Dsonar.login=$SONAR_TOKEN
