CREATE TYPE nivel AS ENUM ('Bacharelado', 'Licenciatura', 'Aperfeiçoamento', 'Especialização', 'Mestrado', 'Doutorado');
CREATE TYPE tipo_instituicao AS ENUM ('Federal', 'Estadual', 'Municipal', 'Particular');
CREATE TYPE sexo AS ENUM ('masculino', 'feminino');
CREATE TYPE visibilidade AS ENUM ('Público', 'Privado', 'Só Egressos');
CREATE TABLE CURSO_OUTRAS_IES_EGRES
(
NOME_CURSO			VARCHAR(150)	NOT NULL,
CODIGO_CURSO		INTEGER	PRIMARY KEY	NOT NULL.
NIVEL_CURSO			nivel			 NOT NULL,
NOME_UNIDADE_ACADEMICA 	VARCHAR(150),
IES_CURSO				VARCHAR(150)	NOT NULL,
TIPO_IES				tipoInstituicao  		NOT NULL,
URL_INSTITUCIONAL		VARCHAR(150)
);

CREATE TABLE EGRESSO
(
NOME_OFICIAL			VARCHAR(150)	NOT NULL,
MATRICULA				INTEGER	    	PRIMARY KEY  NOT NULL,
NOME_MAE				VARCHAR(150)	NOT NULL,
DATA_NASCIMENTO		VARCHAR(10)	NOT NULL,
SEXO					sexo,
EMAIL_ALTERNATIVO		VARCHAR(150),
FOTO_PRINCIPAL			BITSET(1),
FOTOS_ADICINAIS			BITSET(5),
VISIBILIDADE_DADOS		visibilidade		NOT NULL
);

CREATE TABLE HISTORICO_OUTRAS_IES
(
CODIGO_HISTORICO	INTEGER	PRIMARY KEY	NOT NULL,
MES_INICIO				INTEGER		NOT NULL,
ANO_INICIO				INTEGER		NOT NULL,
MES_FIM				INTEGER		NOT NULL,
ANO_FIM				INTEGER		NOT NULL
);

CREATE TABLE LOCALIZACAO_GEOGRAFICA
(
NOME_CURSO			VARCHAR(150)	NOT NULL,
NOME_UNIDADE_FEDERADA	VARCHAR(30)	NOT NULL,
NOME_PAIS				VARCHAR(30)	NOT NULL,
SIGLA_UF				VARCHAR(3)		NOT NULL,
CODIGO_LOCALIZACAO	INTEGER	PRIMARY KEY	NOT NULL,
LATITUDE				NUMERIC(10),
LONGITUDE				NUMERIC(10)
);
