CREATE TABLE AREA_DE_CONHECIMENTO (	NOME VARCHAR(300) NOT NULL,
									CODIGO INTEGER UNSIGNED PRIMARY KEY NOT NULL,
									SUPER_AREA INTEGER UNSIGNED REFERENCES AREA_DE_CONHECIMENTO (CODIGO));

CREATE TABLE CURSO_DA_UFG (	NIVEL ENUM('Bacharelado', 'Licenciatura', 'Aperfeicoamento', 'Especializacao', 'Mestrado', 'Doutorado') NOT NULL,
							TIPO_DE_RESOLUCAO ENUM('CEPEC', 'CONSUNI') NOT NULL,            
							NUMERO_DA_RESOLUCAO INTEGER UNSIGNED PRIMARY KEY NOT NULL,
							E_PRESENCIAL BOOLEAN NOT NULL,
							TURNO ENUM('Matutino', 'Vespertino', 'Integral') NOT NULL,
							UNIDADE_ACADEMICA VARCHAR(200) NOT NULL REFERENCES UNIDADE_ACADEMICA_UFG (NOME),
							AREA_DE_CONHECIMENTO INTEGER UNSIGNED NOT NULL REFERENCES AREA_DE_CONHECIMENTO (CODIGO));

CREATE TABLE HISTORICO_NA_UFG (	NUMERO_MATRICULA_CURSO INTEGER UNSIGNED PRIMARY KEY NOT NULL,
            MES_DE_INICIO INTEGER UNSIGNED NOT NULL,
            ANO_DE_INICIO INTEGER UNSIGNED NOT NULL,
            MES_DE_FIM INTEGER UNSIGNED NOT NULL,
            ANO_DE_FIM INTEGER UNSIGNED NOT NULL,
			CONSTRAINT MES_MENOR_QUE_12 CHECK (MES_DE_INICIO < 13 AND MES_DE_FIM <13),
			CONSTRAINT ANO_FIM_MAIOR_QUE_ANO_INICIO CHECK (ANO_DE_FIM > ANO_DE_INICIO),
            TITULO_DO_TRABALHO_FINAL VARCHAR(500),
            CURSO INTEGER UNSIGNED NOT NULL REFERENCES CURSO_DA_UFG (NUMERO_DA_RESOLUCAO));


CREATE TABLE AVALIACAO_DO_CURSO_PELO_EGRESSO (	HISTORICO INTEGER UNSIGNED NOT NULL REFERENCES HISTORICO_NA_UFG (NUMERO_MATRICULA_CURSO),
												DATA_AVALIACAO DATE NOT NULL,
												MOTIVACAO_ESCOLHA ENUM('Qualidade/Reputacao do Curso', 'Qualidade/Reputacao da IES', 'Gratuidade', 'Outra') NOT NULL,
												SATISFACAO_CURSO INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.SATISFACAO_CURSO <=10),
												CONCEITO_GLOBAL_CURSO INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.CONCEITO_GLOBAL_CURSO <=10),
												PREPARACAO_PARA_MERCADO INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.PREPARACAO_PARA_MERCADO <=10),
												MELHORIA_CAPACIDADE_COMUNICACAO INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.MELHORIA_CAPACIDADE_COMUNICACAO <=10),
												CAPACIDADE_ETICA_RESPONSABILIADE INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.CAPACIDADE_ETICA_RESPONSABILIADE <=10),
												CAPACIDADE_HABILIDADES_AREA_CONHECIMENTO INTEGER UNSIGNED NOT NULL,
												CHECK (AVALIACAO_DO_CURSO_PELO_EGRESSO.CAPACIDADE_HABILIDADES_AREA_CONHECIMENTO <=10),
												COMENTARIO VARCHAR(300));


CREATE TABLE REALIZACAO_DE_PROGRAMA_ACADEMICO (	HISTORICO INTEGER UNSIGNED NOT NULL REFERENCES HISTORICO_NA_UFG (NUMERO_MATRICULA_CURSO),
												TIPO ENUM('Iniciacao_Cientifica', 'Monitoria', 'Extensao', 'Intercambio') NOT NULL,
												DATA_INICIO DATE NOT NULL,
												DATA_FIM DATE NOT NULL,
												DESCRICAO VARCHAR(300) NOT NULL);
